"""message

Revision ID: 688f780d2fa9
Revises: 0e1f827d912c
Create Date: 2024-06-27 13:53:51.464240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688f780d2fa9'
down_revision = '0e1f827d912c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurants_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pizzas_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_restaurant_pizzas_pizzas_id_pizzas'), 'pizzas', ['pizzas_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_restaurant_pizzas_restaurants_id_restaurants'), 'restaurants', ['restaurants_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_restaurant_pizzas_restaurants_id_restaurants'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_restaurant_pizzas_pizzas_id_pizzas'), type_='foreignkey')
        batch_op.drop_column('pizzas_id')
        batch_op.drop_column('restaurants_id')

    # ### end Alembic commands ###
